#!/usr/bin/env node
// Fit-ramp generator CLI — dev-time only, never a build step the site
// depends on (the no-build doctrine holds; the site still serves static
// files). Build contract: v12 Part 22.5 (refusal semantics, drift guard).
//
// Modes:
//   node tools/generate-ramp.mjs --theme light|dark   generate + validate
//   node tools/generate-ramp.mjs                       all configured themes
//   node tools/generate-ramp.mjs --check               drift guard: re-derive
//                                                      committed stops from
//                                                      committed anchors, diff
//   node tools/generate-ramp.mjs --self-test           reference vectors, CVD
//                                                      cross-check, placeholder
//                                                      build, designed refusals
//
// Refusal semantics: any failed check -> exit nonzero, full per-check
// table printed with the failing stop and check named, NO constants
// block emitted. The report prints every computed number whether passing
// or not — the site's whole posture is "show the numbers," and its own
// tooling holds that bar too.

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import {
  buildRamp, hexToOklch, hexToLab, deltaE76, simulateCvd,
  deriveVienotFromPaper, VIENOT_PROTAN, VIENOT_DEUTAN,
} from "./color-ramp.mjs";
import { RAMP_CONFIG, THEME_BACKGROUND, MEANING_COLORS } from "./ramp-config.mjs";

const GENERATOR_VERSION = "1";
const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const COLORS_JS = join(REPO_ROOT, "js", "colors.js");

// ---------------------------------------------------------------------------
// Report printing
// ---------------------------------------------------------------------------

function printReport(report) {
  const { config, anchors, stopDetails, checks, warnings } = report;
  console.log(`  anchors: bad ${config.anchorBad} (L=${anchors.bad.oklch.L.toFixed(3)} C=${anchors.bad.oklch.C.toFixed(3)} h=${anchors.bad.oklch.h.toFixed(1)}°)`);
  console.log(`           good ${config.anchorGood} (L=${anchors.good.oklch.L.toFixed(3)} C=${anchors.good.oklch.C.toFixed(3)} h=${anchors.good.oklch.h.toFixed(1)}°)`);
  console.log(`  arc: ${config.hueArc} | background: ${config.background}`);
  console.log(`  stops: ${stopDetails.map((s) => s.hex + (s.gamutMapped ? "*" : "")).join(" ")}  (* = chroma reduced to fit sRGB gamut)`);
  for (const c of checks) {
    console.log(`  ${c.pass ? "PASS" : "FAIL"} ${c.name}`);
    for (const row of c.rows) {
      const flag = row.pass ? "   " : " ->";
      if (c.id === "endpoint-separation") console.log(`   ${flag} ${row.vision}: ΔE ${row.deltaE}`);
      else if (c.id === "contrast") console.log(`   ${flag} stop ${row.stop} ${row.hex}: ${row.contrast}:1`);
      else if (c.id === "neighbor-separation") console.log(`   ${flag} stops ${row.pair} (${row.vision}): ΔE ${row.deltaE}`);
      else if (c.id === "no-mud") console.log(`   ${flag} stop ${row.stop} ${row.hex}: L=${row.L} C=${row.C} h=${row.h}°`);
      else if (c.id === "meaning-distinctness") console.log(`   ${flag} stop ${row.stop} vs ${row.vs} (${row.vsHex}): min ΔE ${row.minDeltaE} (${row.worstVision}) — ${row.band}`);
    }
  }
  if (warnings.length) {
    console.log(`  ${warnings.length} warning(s) — legal, below the ≥46 precedent, for the felt read:`);
    for (const w of warnings) console.log(`    - ${w}`);
  }
}

// ---------------------------------------------------------------------------
// Constants-block emission + parsing (the drift-guard contract)
// ---------------------------------------------------------------------------

function constName(theme) {
  return theme === "light" ? "SCALE_STOPS_LIGHT" : "SCALE_STOPS_DARK";
}

function emitBlock(theme, result) {
  const { config, checks, warnings } = result.report;
  const summarize = (id) => checks.find((c) => c.id === id);
  const ep = summarize("endpoint-separation").rows.map((r) => `${r.vision} ${r.deltaE}`).join(", ");
  const contrastMin = Math.min(...summarize("contrast").rows.map((r) => r.contrast));
  const neighborMin = Math.min(...summarize("neighbor-separation").rows.map((r) => r.deltaE));
  const meaningMin = Math.min(...summarize("meaning-distinctness").rows.map((r) => r.minDeltaE));
  return [
    `// GENERATED-RAMP BEGIN theme=${theme} anchors=${config.anchorBad},${config.anchorGood} arc=${config.hueArc} background=${config.background} generator=v${GENERATOR_VERSION}`,
    `// Generated by tools/generate-ramp.mjs — do not hand-edit; --check re-derives`,
    `// this block from the committed anchors and fails on any drift.`,
    `// Validated: endpoint ΔE ${ep} | contrast min ${contrastMin}:1 | neighbor min ΔE ${neighborMin} | mud none | meaning-color min ΔE ${meaningMin} (${warnings.length} warning${warnings.length === 1 ? "" : "s"})`,
    `const ${constName(theme)} = [${result.stops.map((h) => `"${h}"`).join(", ")}];`,
    `// GENERATED-RAMP END theme=${theme}`,
  ].join("\n");
}

function parseCommittedBlock(source, theme) {
  const begin = new RegExp(`^// GENERATED-RAMP BEGIN theme=${theme} anchors=(#[0-9a-fA-F]{6}),(#[0-9a-fA-F]{6}) arc=(\\w+) background=(#[0-9a-fA-F]{6}) generator=v(\\S+)$`, "m");
  const m = source.match(begin);
  if (!m) return null;
  const stopsRe = new RegExp(`const ${constName(theme)} = \\[([^\\]]+)\\];`);
  const tail = source.slice(m.index);
  const endIdx = tail.indexOf(`// GENERATED-RAMP END theme=${theme}`);
  if (endIdx === -1) return { error: "BEGIN marker without matching END marker" };
  const blockText = tail.slice(0, endIdx);
  const sm = blockText.match(stopsRe);
  if (!sm) return { error: "block does not contain the stops constant" };
  return {
    anchorBad: m[1],
    anchorGood: m[2],
    hueArc: m[3],
    background: m[4],
    stops: sm[1].split(",").map((s) => s.trim().replace(/"/g, "")),
  };
}

// ---------------------------------------------------------------------------
// generate / check
// ---------------------------------------------------------------------------

function generateTheme(theme) {
  const cfg = RAMP_CONFIG[theme];
  if (!cfg) {
    console.log(`[${theme}] no anchors configured (anchor pick still pending) — nothing to generate.`);
    return { skipped: true };
  }
  const result = buildRamp({
    anchorBad: cfg.anchorBad,
    anchorGood: cfg.anchorGood,
    background: THEME_BACKGROUND[theme],
    hueArc: cfg.hueArc,
    meaningColors: MEANING_COLORS[theme],
  });
  console.log(`[${theme}] ${result.ok ? "VALID" : "REFUSED"}`);
  printReport(result.report);
  if (!result.ok) return { failed: true };
  console.log(`\n[${theme}] constants block for js/colors.js:\n`);
  console.log(emitBlock(theme, result));
  return { ok: true };
}

function runGenerate(themes) {
  let anyFailed = false;
  let anyRan = false;
  for (const theme of themes) {
    const r = generateTheme(theme);
    if (r.failed) anyFailed = true;
    if (!r.skipped) anyRan = true;
  }
  if (anyFailed) process.exit(1); // refusal: nonzero, nothing emitted for the failing theme
  if (!anyRan) console.log("No theme has anchors configured yet — see tools/ramp-config.mjs.");
}

function runCheck() {
  const source = readFileSync(COLORS_JS, "utf8");
  let failed = false;
  // 1. Meaning-color table drift: every hex this tool validates against
  //    must still exist in js/colors.js source.
  for (const theme of ["light", "dark"]) {
    for (const mc of MEANING_COLORS[theme]) {
      if (!source.toLowerCase().includes(mc.hex.toLowerCase())) {
        console.error(`DRIFT: ${theme} meaning-color ${mc.name} ${mc.hex} not found in js/colors.js — the duplicated table in tools/ramp-config.mjs is stale.`);
        failed = true;
      }
    }
  }
  // 2. Generated-block drift: for each theme, committed block and
  //    configured anchors must agree, and re-generation must reproduce
  //    the committed stops exactly.
  for (const theme of ["light", "dark"]) {
    const cfg = RAMP_CONFIG[theme];
    const block = parseCommittedBlock(source, theme);
    if (block && block.error) {
      console.error(`DRIFT [${theme}]: ${block.error}`);
      failed = true;
      continue;
    }
    if (!cfg && !block) {
      console.log(`[${theme}] clean: no anchors configured, no generated block committed (interim hand-set stops in place).`);
      continue;
    }
    if (cfg && !block) {
      console.error(`DRIFT [${theme}]: anchors configured but js/colors.js has no generated block — run the generator and commit its output.`);
      failed = true;
      continue;
    }
    if (!cfg && block) {
      console.error(`DRIFT [${theme}]: js/colors.js carries a generated block but tools/ramp-config.mjs has no anchors — config and committed output disagree.`);
      failed = true;
      continue;
    }
    if (cfg.anchorBad !== block.anchorBad || cfg.anchorGood !== block.anchorGood || cfg.hueArc !== block.hueArc || THEME_BACKGROUND[theme] !== block.background) {
      console.error(`DRIFT [${theme}]: configured anchors/arc/background (${cfg.anchorBad},${cfg.anchorGood},${cfg.hueArc},${THEME_BACKGROUND[theme]}) != committed block (${block.anchorBad},${block.anchorGood},${block.hueArc},${block.background}).`);
      failed = true;
      continue;
    }
    const regen = buildRamp({
      anchorBad: cfg.anchorBad,
      anchorGood: cfg.anchorGood,
      background: THEME_BACKGROUND[theme],
      hueArc: cfg.hueArc,
      meaningColors: MEANING_COLORS[theme],
    });
    if (!regen.ok) {
      console.error(`DRIFT [${theme}]: committed anchors no longer validate (a threshold or meaning-color changed since generation).`);
      printReport(regen.report);
      failed = true;
      continue;
    }
    if (regen.stops.join() !== block.stops.join()) {
      console.error(`DRIFT [${theme}]: committed stops [${block.stops.join(" ")}] != regenerated [${regen.stops.join(" ")}] — a hand-edited hex cannot pretend it was generated.`);
      failed = true;
      continue;
    }
    console.log(`[${theme}] clean: committed stops re-derive exactly from committed anchors.`);
  }
  process.exit(failed ? 1 : 0);
}

// ---------------------------------------------------------------------------
// Self-test (v12 Part 22.3 reference vectors, 22.5 CVD sourcing
// cross-check, 22.10 placeholder-anchor build, designed refusals)
// ---------------------------------------------------------------------------

// PLACEHOLDER anchors — self-test only, never a product decision. The
// anchor pick is an open call that belongs to the product owner; these
// exist so the mechanism is exercised end-to-end today. They are
// red-family -> green-family on the LONG arc (the first config worth
// testing per the spec's own note), REGENERATED by this mechanism from
// two anchors — never a prior candidate's five hexes adopted as-is.
const PLACEHOLDER_DARK = { anchorBad: "#e4744b", anchorGood: "#d3f7df", hueArc: "longer" };
// Light-theme placeholder kept for the DESIGNED-REFUSAL assertions: a
// systematic 4,500-config search over the red-family/green-family
// anchor space (documented in the build notes) found zero light-theme
// pairs passing all five checks — the refusal itself is the expected,
// asserted outcome on cream paper.
const PLACEHOLDER_LIGHT = { anchorBad: "#8a1f10", anchorGood: "#00674f" };

function runSelfTest() {
  let failures = 0;
  const assert = (name, cond, detail = "") => {
    console.log(`  ${cond ? "ok" : "FAIL"} ${name}${detail ? ` — ${detail}` : ""}`);
    if (!cond) failures++;
  };
  const roundTo = (x, dp) => Number(x.toFixed(dp));

  console.log("[1] Reference test vectors (must reproduce the ruled spec values):");
  {
    const o1 = hexToOklch("#7a2213");
    assert("OKLCH(#7a2213) = L 0.391 C 0.125 h 32.2°",
      roundTo(o1.L, 3) === 0.391 && roundTo(o1.C, 3) === 0.125 && roundTo(o1.h, 1) === 32.2,
      `got L ${roundTo(o1.L, 3)} C ${roundTo(o1.C, 3)} h ${roundTo(o1.h, 1)}`);
    const o2 = hexToOklch("#006726");
    assert("OKLCH(#006726) = L 0.448 C 0.130 h 148.1°",
      roundTo(o2.L, 3) === 0.448 && roundTo(o2.C, 3) === 0.13 && roundTo(o2.h, 1) === 148.1,
      `got L ${roundTo(o2.L, 3)} C ${roundTo(o2.C, 3)} h ${roundTo(o2.h, 1)}`);
    const lab = hexToLab("#7a2213");
    assert("Lab(#7a2213) = (27.65, 37.31, 30.94)",
      roundTo(lab[0], 2) === 27.65 && roundTo(lab[1], 2) === 37.31 && roundTo(lab[2], 2) === 30.94,
      `got (${lab.map((v) => roundTo(v, 2)).join(", ")})`);
    assert("CIE76(#370036, #7a2213) = 54.1 (the standing separation figure)",
      roundTo(deltaE76("#370036", "#7a2213"), 1) === 54.1,
      `got ${roundTo(deltaE76("#370036", "#7a2213"), 1)}`);
    assert("CIE76(#ED3D2B, #E16095) = 55.5",
      roundTo(deltaE76("#ED3D2B", "#E16095"), 1) === 55.5,
      `got ${roundTo(deltaE76("#ED3D2B", "#E16095"), 1)}`);
  }

  console.log("[2] CVD simulation — two-path cross-check (precomputed reference matrices vs an independent re-derivation from the published method):");
  {
    const derived = deriveVienotFromPaper();
    let maxDiff = 0;
    for (let i = 0; i < 3; i++) for (let j = 0; j < 3; j++) {
      maxDiff = Math.max(maxDiff,
        Math.abs(derived.protan[i][j] - VIENOT_PROTAN[i][j]),
        Math.abs(derived.deutan[i][j] - VIENOT_DEUTAN[i][j]));
    }
    assert("derived-from-method matrices match precomputed reference within 1e-4", maxDiff < 1e-4, `max |diff| ${maxDiff.toExponential(2)}`);
    assert("protan preserves white and blue (the method's own anchor invariants)",
      simulateCvd("#ffffff", "protan") === "#ffffff" && simulateCvd("#0000ff", "protan") === "#0000ff");
    assert("deutan preserves white and blue",
      simulateCvd("#ffffff", "deutan") === "#ffffff" && simulateCvd("#0000ff", "deutan") === "#0000ff");
  }

  console.log("[3] Placeholder build, dark theme (mechanism must be able to PASS and emit):");
  {
    const r = buildRamp({ ...PLACEHOLDER_DARK, background: THEME_BACKGROUND.dark, meaningColors: MEANING_COLORS.dark });
    assert("dark placeholder passes all five checks", r.ok === true,
      r.ok ? "" : "failing: " + r.report.checks.filter((c) => !c.pass).map((c) => c.id).join(","));
    assert("five stops emitted", !!r.stops && r.stops.length === 5);
    if (r.ok) {
      const block = emitBlock("dark", r);
      const parsed = parseCommittedBlock(block, "dark");
      assert("emitted block round-trips through the drift-guard parser",
        !!parsed && !parsed.error && parsed.stops.join() === r.stops.join()
        && parsed.anchorBad === PLACEHOLDER_DARK.anchorBad && parsed.hueArc === "longer");
      console.log("  placeholder dark stops:", r.stops.join(" "), `(${r.report.warnings.length} legal warnings)`);
    }
  }

  console.log("[4] Designed refusals (refusing is the mechanism working — v12 Part 22.4's own predictions):");
  {
    const shorter = buildRamp({ ...PLACEHOLDER_LIGHT, hueArc: "shorter", background: THEME_BACKGROUND.light, meaningColors: MEANING_COLORS.light });
    const shorterFails = shorter.report.checks.filter((c) => !c.pass).map((c) => c.id);
    assert("light red->green SHORTER arc refuses, mud check named", shorter.ok === false && shorterFails.includes("no-mud"), `failing: ${shorterFails.join(",")}`);
    assert("refusal emits no stops", shorter.stops === null);
    const muddy = shorter.report.checks.find((c) => c.id === "no-mud").rows.filter((r2) => !r2.pass);
    console.log("  arithmetic coffee-stain stops the mud check caught:", muddy.map((r2) => r2.hex).join(" "));

    const longer = buildRamp({ ...PLACEHOLDER_LIGHT, hueArc: "longer", background: THEME_BACKGROUND.light, meaningColors: MEANING_COLORS.light });
    const longerFails = longer.report.checks.filter((c) => !c.pass).map((c) => c.id);
    assert("light red->green LONGER arc also refuses on cream (endpoint separation under dichromacy + fixed-color collisions)",
      longer.ok === false && longerFails.includes("endpoint-separation") && longerFails.includes("meaning-distinctness"),
      `failing: ${longerFails.join(",")}`);
  }

  console.log("[5] Drift-guard parser edge cases:");
  {
    assert("no block in a source without markers", parseCommittedBlock("const SCALE_STOPS_LIGHT = [1];", "light") === null);
    const broken = "// GENERATED-RAMP BEGIN theme=light anchors=#111111,#222222 arc=longer background=#F2E8D5 generator=v1\nconst SCALE_STOPS_LIGHT = [\"#111111\"];";
    const parsed = parseCommittedBlock(broken, "light");
    assert("BEGIN without END is reported as an error, not silently accepted", !!parsed && parsed.error === "BEGIN marker without matching END marker");
  }

  console.log(failures === 0 ? "\nSELF-TEST PASS" : `\nSELF-TEST FAIL (${failures} failing assertion${failures === 1 ? "" : "s"})`);
  process.exit(failures === 0 ? 0 : 1);
}

// ---------------------------------------------------------------------------
// Entry
// ---------------------------------------------------------------------------

const args = process.argv.slice(2);
if (args.includes("--self-test")) runSelfTest();
else if (args.includes("--check")) runCheck();
else {
  const themeIdx = args.indexOf("--theme");
  const themes = themeIdx !== -1 ? [args[themeIdx + 1]] : ["light", "dark"];
  for (const t of themes) {
    if (t !== "light" && t !== "dark") {
      console.error(`Unknown theme "${t}" — use light or dark.`);
      process.exit(2);
    }
  }
  runGenerate(themes);
}
